# Generated by Django 5.1 on 2024-08-14 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.TextField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Chat History',
                'verbose_name_plural': 'Chat Histories',
                'db_table': 'ChatHistory',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=30, verbose_name='First Name')),
                ('name_last', models.CharField(max_length=30, verbose_name='Last Name')),
                ('photo', models.URLField(verbose_name='Photo URL')),
            ],
            options={
                'verbose_name': 'Expert',
                'verbose_name_plural': 'Experts',
                'db_table': 'Experts',
            },
        ),
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('country_code', models.CharField(max_length=20, verbose_name='Country_Short')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('region_code', models.CharField(max_length=20, verbose_name='Region_Short')),
            ],
            options={
                'verbose_name': 'Geography',
                'verbose_name_plural': 'Geographies',
                'db_table': 'Geography',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=100, verbose_name='Employer')),
                ('industry', models.CharField(max_length=100, verbose_name='Industry')),
                ('function', models.CharField(max_length=100, verbose_name='Function')),
                ('role', models.CharField(max_length=100, verbose_name='Role')),
                ('years', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Years')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='aichat_chat.expert')),
                ('geography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='aichat_chat.geography')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'db_table': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500, verbose_name='Topic')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='aichat_chat.expert')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'Topics',
            },
        ),
    ]
