# Generated by Django 5.1 on 2024-08-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Language Code')),
                ('name', models.CharField(max_length=50, verbose_name='Language Name')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='aichat_chat.expert')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='aichat_chat.language')),
            ],
            options={
                'unique_together': {('expert', 'language')},
            },
        ),
    ]
