# Generated by Django 5.1 on 2024-08-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0002_language_expertlanguage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expertlanguage',
            table='aichat_expert_language',
        ),
        migrations.AlterModelTable(
            name='language',
            table='aichat_language',
        ),
    ]
