# Generated by Django 5.1 on 2024-08-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0003_alter_expertlanguage_table_alter_language_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='translated_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Language Name'),
        ),
    ]
