# Generated by Django 5.1 on 2024-09-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0004_language_translated_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('top_level_domain', models.CharField(blank=True, max_length=200, null=True)),
                ('date_accessed', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Website', 'Website'), ('Document', 'Document')], max_length=100, null=True)),
                ('embedding', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vector',
                'verbose_name_plural': 'Vectors',
                'db_table': 'Vector',
            },
        ),
    ]
