# Generated by Django 5.1 on 2024-09-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0005_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vector',
            name='type',
            field=models.CharField(blank=True, choices=[('Website', 'Website'), ('Document', 'Document'), ('Image', 'Image')], max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='vector',
            table='aichat_vector',
        ),
    ]
