# Generated by Django 5.1 on 2024-09-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0007_vector_user_alter_vector_top_level_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vector',
            old_name='url',
            new_name='source',
        ),
    ]
