# Generated by Django 5.1 on 2024-09-26 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0008_rename_url_vector_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RagUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aichat_ragurls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RagUrl',
                'verbose_name_plural': 'RagUrls',
                'db_table': 'aichat_ragurl',
            },
        ),
    ]
