# Generated by Django 5.1 on 2024-09-26 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0009_ragurl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ragurl',
            name='include_subdomains',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='ragurl',
            unique_together={('url', 'user')},
        ),
    ]
