# Generated by Django 5.1 on 2024-10-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0011_alter_ragurl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=100, null=True),
        ),
    ]
