# Generated by Django 5.1 on 2024-10-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0012_vector_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
