# Generated by Django 5.1 on 2024-10-14 03:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0013_vector_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RagUrl',
            new_name='RagSource',
        ),
    ]
