# Generated by Django 5.1 on 2024-10-14 03:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0014_rename_ragurl_ragsource'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ragsource',
            old_name='url',
            new_name='source',
        ),
        migrations.AlterUniqueTogether(
            name='ragsource',
            unique_together={('source', 'user')},
        ),
    ]
