# Generated by Django 5.1 on 2024-10-14 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0016_alter_ragsource_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ragsource',
            options={'verbose_name': 'RagSource', 'verbose_name_plural': 'RagSources'},
        ),
        migrations.AlterModelTable(
            name='ragsource',
            table='aichat_ragsource',
        ),
    ]
