# Generated by Django 5.1 on 2024-10-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0017_alter_ragsource_options_alter_ragsource_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragsource',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
