# Generated by Django 5.1 on 2024-10-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0018_ragsource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragsource',
            name='include_subdomains',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
