# Generated by Django 5.1 on 2024-10-15 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0019_alter_ragsource_include_subdomains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ragsource',
            unique_together={('source', 'user')},
        ),
        migrations.AddField(
            model_name='ragsource',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='ragsource',
            name='type',
            field=models.CharField(blank=True, choices=[('Website', 'Website'), ('Document', 'Document'), ('Image', 'Image')], max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ragsource',
            unique_together={('document', 'user'), ('source', 'user')},
        ),
    ]
