# Generated by Django 5.1 on 2024-10-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0020_alter_ragsource_unique_together_ragsource_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragsource',
            name='type',
            field=models.CharField(blank=True, choices=[('website', 'website'), ('document', 'document'), ('image', 'image')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vector',
            name='type',
            field=models.CharField(blank=True, choices=[('website', 'website'), ('document', 'document'), ('image', 'image')], max_length=100, null=True),
        ),
    ]
