# Generated by Django 5.1 on 2024-10-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0021_alter_ragsource_type_alter_vector_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ragsource',
            unique_together=set(),
        ),
    ]
