# Generated by Django 5.1 on 2024-10-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0022_alter_ragsource_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragsource',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
