# Generated by Django 5.1 on 2024-10-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0023_alter_ragsource_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ragsource',
            old_name='document',
            new_name='file_path',
        ),
    ]
