# Generated by Django 5.1 on 2024-10-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0024_rename_document_ragsource_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragsource',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='new_path/'),
        ),
    ]
