# Generated by Django 5.1 on 2024-10-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0025_alter_ragsource_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragsource',
            name='file_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ragsource',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
