# Generated by Django 5.1 on 2024-10-29 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0026_ragsource_file_size_alter_ragsource_file_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retriever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=255)),
                ('search_type', models.CharField(max_length=50)),
                ('search_kwargs', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aichat_retriever', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retriever',
                'verbose_name_plural': 'Retrievers',
                'db_table': 'aichat_retrievers',
            },
        ),
    ]
