# Generated by Django 5.1 on 2024-10-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0027_retriever'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retriever',
        ),
    ]
