"""
Django settings for rag_expertchat project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from dotenv import load_dotenv
import logging
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Basic security settings
SECRET_KEY = os.getenv('SECRET_KEY', 'your-secret-key-here')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '35.238.181.177',  # Your server IP
    'kebayorantechnologies.com',
    'www.kebayorantechnologies.com',
    'rag-app'
]

# URL prefix configuration for reverse proxy
FORCE_SCRIPT_NAME = os.getenv('FORCE_SCRIPT_NAME', None)
USE_X_FORWARDED_HOST = os.getenv('USE_X_FORWARDED_HOST', 'False').lower() == 'true'


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # RAG-specific apps
    'aichat_chat',
    'aichat_users',
    
    # Third party (add as needed)
    'widget_tweaks',  # If used in your templates
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Adds CSP-Report-Only (with per-request nonce), Permissions-Policy and COOP.
    # Sits high in the stack so request.csp_nonce is set before templates render.
    'rag_expertchat.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # For static files
]

# Security headers handled by Django's own middleware (Part A).
# HSTS is intentionally left to the TLS-terminating edge to avoid a second /
# conflicting Strict-Transport-Security header from the app layer.
SECURE_CONTENT_TYPE_NOSNIFF = True                      # X-Content-Type-Options: nosniff
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'                                # no view legitimately iframes itself

# Defence-in-depth for session/CSRF cookies (the app is served over HTTPS at the edge).
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False  # CSRF token is read by JS (see csrf-token meta tag)

ROOT_URLCONF = 'rag_expertchat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rag_expertchat.wsgi.application'


# CSRF settings for reverse proxy
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else []

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Custom email authentication (from your homepage)
AUTHENTICATION_BACKENDS = [
    'rag_expertchat.authentication_backend.EmailAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Token settings -----------------------------------------------------
TOKEN_TIMEOUT = int(24*60) # Unit is seconds, so 15 min. = 900 sec.
SESSION_COOKIE_AGE = int(24*60) # Unit is seconds, so 15 mins = 900 sec.
SESSION_EXPIRE_AT_BROWSER_CLOSE=False # If true, user is logged out every time browser is closed.
SESSION_SAVE_EVERY_REQUEST=True # If True, SESSION_COOKIE_AGE timer resets every time there is user activity.


# Internationalization --------------------------------------------
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Jakarta'  # Keeping your timezone
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'collected_static'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Where you'll put RAG-specific static files
]


# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Upload hardening (Part B): per-file cap enforced in RagDocForm.clean_file_path.
MAX_UPLOAD_SIZE_MB = 25
# Reject oversized request bodies before they reach the view.
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_UPLOAD_SIZE_MB * 1024 * 1024  # 25 MB

# Session settings (adapted from your homepage)
SESSION_COOKIE_AGE = 24 * 60 * 60  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Environment-specific settings for RAG system
PINECONE_API_KEY = os.getenv('PINECONE_API_KEY')
HUGGINGFACE_TOKEN = os.getenv('HUGGINGFACE_TOKEN')
TOKENIZER_MAX_LENGTH_FIXED = 512


# Logging (simplified from your homepage)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {pathname}:{lineno} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
