# Generated by Django 5.1 on 2024-08-14 15:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(blank=True, default='hist_rag', max_length=64, null=True)),
                ('suggest_experts', models.BooleanField(blank=True, default=True, null=True)),
                ('experts_suggested_number', models.IntegerField(blank=True, default=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('weight_years', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('weight_industry', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('weight_role', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('weight_topic', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('weight_geography', models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('response_length', models.IntegerField(blank=True, default=4, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(200)])),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, default=0.3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('chunk_size', models.IntegerField(blank=True, default=1000, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(30000)])),
                ('chunk_overlap', models.DecimalField(blank=True, decimal_places=2, default=0.3, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.75)])),
                ('preferred_language', models.CharField(blank=True, default='en', max_length=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aichat_userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aichat_userprofile',
            },
        ),
    ]
