# Generated by Django 5.1 on 2024-08-16 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_chat', '0001_initial'),
        ('aichat_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_as_favorite_by', to='aichat_chat.expert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aichat_favorite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aichat_favorites',
            },
        ),
    ]
