# Generated by Django 5.1 on 2024-08-16 05:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0002_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='added',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
