# Generated by Django 5.1 on 2024-08-28 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0004_userprofile_expert_speaks_my_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='langchain_k',
            field=models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='top_p',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
