# Generated by Django 5.1 on 2024-08-28 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0005_userprofile_langchain_k_userprofile_top_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='top_p',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
