# Generated by Django 5.1 on 2024-08-30 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0006_alter_userprofile_top_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chat_history_window',
            field=models.IntegerField(blank=True, default=20, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
