# Generated by Django 5.1 on 2024-09-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0010_userprofile_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rag_sources',
            field=models.CharField(blank=True, default='docs', max_length=100, null=True),
        ),
    ]
