# Generated by Django 5.1 on 2024-09-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0011_userprofile_rag_sources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='rag_sources',
            new_name='rag_sources_shown',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rag_sources_used',
            field=models.CharField(blank=True, default='docs', max_length=100, null=True),
        ),
    ]
