# Generated by Django 5.1 on 2024-10-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0012_rename_rag_sources_userprofile_rag_sources_shown_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rag_sources_shown',
            field=models.CharField(blank=True, default='all', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='rag_sources_used',
            field=models.CharField(blank=True, default='all', max_length=100, null=True),
        ),
    ]
