# Generated by Django 5.1 on 2024-10-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0013_alter_userprofile_rag_sources_shown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tokenization_and_vectorization_model',
            field=models.CharField(blank=True, default='bert-base-multilingual-cased', max_length=100, null=True),
        ),
    ]
