# Generated by Django 5.1 on 2024-10-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0014_userprofile_tokenization_and_vectorization_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preprocessing_model',
            field=models.CharField(blank=True, default='en_core_web_sm', max_length=100, null=True),
        ),
    ]
