# Generated by Django 5.1 on 2024-10-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0015_userprofile_preprocessing_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='similarity_metric',
            field=models.CharField(blank=True, default='cosine', max_length=100, null=True),
        ),
    ]
