# Generated by Django 5.1 on 2024-10-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0016_userprofile_similarity_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='retriever_model',
            field=models.CharField(blank=True, default='gpt-4o-mini', max_length=100, null=True),
        ),
    ]
