# Generated by Django 5.1 on 2024-10-30 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0017_userprofile_retriever_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='employer',
            new_name='user_employer',
        ),
    ]
