# Generated by Django 5.1 on 2024-10-31 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0018_rename_employer_userprofile_user_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='chat_history_window',
            field=models.IntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
