# Generated by Django 5.1 on 2024-11-15 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aichat_users', '0019_alter_userprofile_chat_history_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preprocessing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experts_suggested_number',
            field=models.IntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
